# Generated by Django 4.0.4 on 2022-04-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='attribute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
