# Generated by Django 4.0.4 on 2022-05-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_listattributes_alter_attributes_pathology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listattributes',
            name='la_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listattributes',
            name='la_value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
