# Generated by Django 4.0.4 on 2022-05-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_listattributes_la_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listattributes',
            name='la_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='listattributes',
            name='la_value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
