# Generated by Django 4.0.4 on 2022-05-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_listattributes_la_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='attr_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='attr_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
